# These are Cloud Build steps. You can read more about cloud build here:
# https://cloud.google.com/cloud-build/docs/
# All these steps sharing a filesystem between each other.
steps:
# ↓↓↓↓↓↓↓ Start of Continuous Integration Part ↓↓↓↓↓↓↓↓↓↓↓↓ #####
######### This part will test if Notebook fully executable #####
  # First, we need to clone the repository that we need to test.
  # This will also clone submodules that are used as dependancies.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--recurse-submodules', 'https://github.com/lukmanr/cicd-notebooks-aiplatform']
  # Next, we need to clone the repository containing the tools for executing notebooks.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--recurse-submodules', 'https://github.com/GoogleCloudPlatform/ai-platform-samples']
  # Next, we need to checkout the exact commit that we need to test. Otherwise, Cloud Build will be testing the master.
  # The variable $COMMIT_SHA is provided by the Cloud Build. You can find more about Cloud Build variables here:
  # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', '$COMMIT_SHA']
  dir: 'cicd-notebooks-aiplatform'
  # This will start notebook background execution.
  # You can read more about the background execution here:
  # https://blog.kovalevskyi.com/how-to-submit-jupyter-notebook-for-overnight-training-on-gcp-4ce1b0cd4d0d
- name: 'google/cloud-sdk:237.0.0'
  args: ['-c', './run_test.sh']
  dir: 'cicd-notebooks-aiplatform'
  entrypoint: '/bin/bash'
  # The secret is needed since we are using Google Map API Key in the Notebook. The notebook just reads the key from the env variables.
  # You can read more about Cloud Build Secrets here:
  # https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials
  secretEnv: ['API_KEY']
# ↑↑↑↑↑↑↑ End of Continuous Integration Part ↑↑↑↑↑↑↑↑↑↑↑↑↑###############
######### Execution will not process further if notebook is broken #####
# ↓↓↓↓↓↓↓ Start of Continuous Delivery Part ↓↓↓↓↓↓↓↓↓↓↓↓ ################
######### This part will generate actual artifact  #####################
  # Our production system contains 2 parts
  # * Cloud function that can execute notebook daily
  # * Notebooks executor that is used by cloud function to execute notebooks
  #
  #  Next step creates an archive with notebook executor.
- name: 'google/cloud-sdk:237.0.0'
  args: ['-c', 'tar -zcvf live.tar.gz demo.ipynb ../ai-platform-samples/notebooks/gcp-notebook-executor/notebook_executor.sh ../ai-platform-samples/notebooks/gcp-notebook-executor/utils.sh run_notebook_instance.sh']
  dir: 'cicd-notebooks-aiplatform'
  entrypoint: '/bin/bash'
  # Archive uploaded to the place where the production system expects it.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'live.tar.gz', 'gs://dl-platform-temp/notebook-ci-showcase/live.tar.gz']
  dir: 'cicd-notebooks-aiplatform'
  # Now we zip the folder with the cloud function that we want to use on a daily basis.
- name: 'google/cloud-sdk:237.0.0'
  args: ['-c', 'apt update && apt install -y zip && zip deploy.zip *']
  dir: 'cicd-notebooks-aiplatform/deploy'
  entrypoint: '/bin/bash'
  # Archive with cloud function uploaded to the place where the production system expects it.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'deploy.zip', 'gs://dl-platform-temp/notebook-ci-showcase/deploy.zip']
  dir: 'notebooks/notebooks-ci-showcase/deploy'
  # For the next step, the cloud build service account must be granted the Cloud Functions Developer permission (not default).
- name: 'google/cloud-sdk:237.0.0'
  args: ['gcloud', 'functions', 'deploy', 'demo-notebook-function', '--trigger-topic=demo-notebook', '--region=us-central1', '--source=gs://dl-platform-temp/notebook-ci-showcase/deploy.zip']
# ↑↑↑↑↑↑↑ End of Continuous Delivery Part ↑↑↑↑↑↑↑↑↑↑↑↑↑##################
######### This part will generate actual artifact  #####################
secrets:
- kmsKeyName: projects/deeplearning-platform/locations/global/keyRings/api_key/cryptoKeys/google_maps_api
  secretEnv:
    API_KEY: CiQAqOZsWlDTXTRk/yjMO1BmEwto8Kboq90JG9zOuhizXsVO6fQSUQD7A7YryCuYQ+t6h9IL9Of6M+qCg/SezgvB/efTAGHhfzOYqa9mNMlECMo5hgnzpNjq6pPCauASAy8+VB+H4SLOfT9drLlpQTgxW3zTpAxtTQ==
